# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - run: dotnet workload install maui-ios
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src/
      
    - name: Build
      run: dotnet build -f net8.0-ios -c Release --no-restore 
      working-directory: src/
      
    
